# Object Oriented Programming in Python

In [48]:
import numpy as np
import pandas as pd
from datetime import date, datetime, time
import pytz

## Constructor

In [5]:
# build an instance of class range
r = range(100)
r

range(0, 100)

In [6]:
type(r)

range

In [7]:
# constructor class list adapt iterable object into a list
l = list(r)
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [12]:
list()

[]

In [14]:
inputCount = '125'
count = int(inputCount)
count

125

In [16]:
# ValueError: invalid literal for int() with base 10: 'not an integer'
# int('not an integer')

In [17]:
for inputFloat in '12.5', '1.345E-23', 'NaN', 'inf':
    f = float(inputFloat)
    print(f)

12.5
1.345e-23
nan
inf


In [25]:
df = pd.DataFrame(
    (
        ("Pau", 77000, 64),
        ("Toulouse", 470000, 31),
        ("Montpellier", 290000, 34),
    ),
    columns=['name', 'population', 'department']
)
df

name  population  department
0          Pau       77000          64
1     Toulouse      470000          31
2  Montpellier      290000          34

In [26]:
 type(df)

pandas.core.frame.DataFrame

In [29]:
# constructor ndarray: exists but not to be used directly
# => use functions instead
a = np.ndarray((5,5))
a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78019082e-306, 7.56596412e-307],
       [1.33511018e-306, 1.33511969e-306, 6.23037996e-307,
        1.69121639e-306, 1.95821439e-306],
       [6.23037657e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307],
       [7.56601165e-307, 1.69118787e-306, 1.11261298e-306,
        8.90104239e-307, 1.60219035e-306],
       [6.89805151e-307, 1.78020169e-306, 1.42410974e-306,
        6.01334412e-154, 6.01347002e-154]])

In [33]:
a1 = np.empty((10,10))
a2 = np.zeros((10,10))
a3 = np.random.normal(12.0, 3.5, (10,10))

In [34]:
a1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
a2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
a3

array([[11.128004  , 10.21202933,  9.67570352, 14.65988288,  6.27374022,
         9.26765562, 16.47781478,  9.23177001, 10.14411625, 14.09668446],
       [12.46968453, 17.89157709, 12.5379358 , 11.27948113, 20.04003381,
         8.88985398, 17.5286866 , 14.9480588 , 14.58602078, 15.57057483],
       [12.8437956 ,  5.56474015, 10.32600484,  7.94357876,  9.60536318,
        18.21013371, 10.14408122,  9.11505602,  9.54498683,  9.65705022],
       [12.25432347,  8.74423435,  8.70476942,  9.07495625, 11.12926727,
        10.79291499, 11.08257522, 11.9300491 ,  8.78174536, 12.59700581],
       [ 9.15141924, 13.97574813, 14.95846796, 16.92529729,  9.94260242,
        12.95079625,  5.98527974, 12.69893356,  9.13338729, 16.24480137],
       [ 6.44994459, 13.85486491, 10.00923723,  5.92411322, 14.81578549,
        15.17821848,  8.40119044,  8.42635523, 16.47941025, 16.63475177],
       [ 7.25829487, 10.42649854, 13.98349796, 15.89225467, 10.27170333,
        12.79033781, 18.71840825, 11.23773768

In [38]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [47]:
tz = pytz.timezone('America/La_Paz')
d = date(2024, 2, 29)
dt = datetime(2024, 2, 29, 14, 30)
dt2 = datetime(2024, 2, 29, 14, 30, 20, 125001, tz)
d, dt, dt2

(datetime.date(2024, 2, 29),
 datetime.datetime(2024, 2, 29, 14, 30),
 datetime.datetime(2024, 2, 29, 14, 30, 20, 125001, tzinfo=<DstTzInfo 'America/La_Paz' LMT-1 day, 19:27:00 STD>))

In [54]:
# build temporal object without constructor
d2 = date.today()
dt3 = datetime.now()
dt4 = datetime.now(tz)
d2, dt3, dt3.time(), dt4

(datetime.date(2024, 2, 6),
 datetime.datetime(2024, 2, 6, 10, 5, 7, 928176),
 datetime.time(10, 5, 7, 928176),
 datetime.datetime(2024, 2, 6, 5, 5, 7, 928176, tzinfo=<DstTzInfo 'America/La_Paz' -04-1 day, 20:00:00 STD>))

Summary:
- class = object type (model)
- object = instance of a class

## Attributes
- attribute = data part of an object

In [56]:
d.year, d.month, d.day

(2024, 2, 29)

In [57]:
dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second, dt.microsecond, dt.tzinfo

(2024, 2, 29, 14, 30, 0, 0, None)

In [59]:
a3.shape

(10, 10)

In [60]:
a3.dtype

dtype('float64')

In [61]:
a3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [65]:
# DataFrame: dynamic attribute for each column (when possible)
df.name

0            Pau
1       Toulouse
2    Montpellier
Name: name, dtype: object

## Methods and operators

### visible methods
start with a letter

In [66]:
# append method of class list
l.append(12)

In [68]:
l.append

<function list.append(object, /)>

In [67]:
dt.time()

datetime.time(14, 30)

In [69]:
dt.time

<function datetime.time>

In [70]:
d.strftime("%d/%m/%Y")

'29/02/2024'

### Masked methods
name: ```__mymethod__```
usage: 
- operator (```__add__```)
- builtin function: len (```__len__```)
- with block: ```__enter__, __exit__```

In [74]:
len(l)

101

In [76]:
l.__len__

<method-wrapper '__len__' of list object at 0x00000229D18FBA40>

In [77]:
l.__len__()

101

In [79]:
# DataFrame: len = number of rows
len(df)

3

In [81]:
# ndarray: size of first dimension
len(a3)

10

In [83]:
# TypeError: object of type 'int' has no len()
# len(123)

In [84]:
[1, 2, 3] + [7, 8, 9]

[1, 2, 3, 7, 8, 9]

In [85]:
list.__add__

<slot wrapper '__add__' of 'list' objects>

In [86]:
a1 + a2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
np.ndarray.__add__

<slot wrapper '__add__' of 'numpy.ndarray' objects>

In [89]:
a4 = a1 + 4
a4

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [94]:
# method called: __iadd__
a4 += 2
a4

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [91]:
dir(a4)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [92]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [93]:
[ m for m in dir(a4) if 'add' in m ]

['__add__', '__iadd__', '__radd__']

In [97]:
city = "Pau"
[ m for m in dir(city) if 'add' in m ]

['__add__']

In [99]:
# when __iadd__ is not available, __add__ is called (new object)
# city = city.__add__(", city of king Henri IV")
city += ", city of king Henri IV"
city

'Pau, city of king Henri IV, city of king Henri IV'

In [100]:
[ m for m in dir(a4) if m.startswith('__') ]

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new_

In [ ]:
# '__abs__' => builtin function abs
#  '__add__' => operator + on left operand
#  '__and__' => operator &
#  '__array__',
#  '__array_finalize__',
#  '__array_function__',
#  '__array_interface__',
#  '__array_prepare__',
#  '__array_priority__',
#  '__array_struct__',
#  '__array_ufunc__',
#  '__array_wrap__',
#  '__bool__',
#  '__buffer__',
#  '__class__',
#  '__class_getitem__',
#  '__complex__',
#  '__contains__',
#  '__copy__',
#  '__deepcopy__',
#  '__delattr__',
#  '__delitem__',
#  '__dir__',
#  '__divmod__' => builtin function divmod()
#  '__dlpack__',
#  '__dlpack_device__',
#  '__doc__',
#  '__eq__' => operator ==
#  '__float__',
#  '__floordiv__' => operator // on left operand
#  '__format__',
#  '__ge__' => operator >= (greater or equal)
#  '__getattribute__',
#  '__getitem__',
#  '__getstate__',
#  '__gt__' => operator >= (greater)
#  '__hash__',
#  '__iadd__' => operator +=
#  '__iand__',
#  '__ifloordiv__',
#  '__ilshift__',
#  '__imatmul__',
#  '__imod__',
#  '__imul__',
#  '__index__',
#  '__init__',
#  '__init_subclass__',
#  '__int__',
#  '__invert__',
#  '__ior__',
#  '__ipow__',
#  '__irshift__',
#  '__isub__',
#  '__iter__',
#  '__itruediv__',
#  '__ixor__',
#  '__le__' => operator <= (less or equal)
#  '__len__' => builtin function len()
#  '__lshift__',
#  '__lt__' => operator < (less than)
#  '__matmul__',
#  '__mod__' => operator % on left operand
#  '__mul__' => operator * on left operand
#  '__ne__' => operator != (not equals)
#  '__neg__',
#  '__new__',
#  '__or__',
#  '__pos__',
#  '__pow__' => operator ?? on left operand
#  '__radd__' => operator + on right operand
#  '__rand__',
#  '__rdivmod__' => builtin function divmod on right operand
#  '__reduce__',
#  '__reduce_ex__',
#  '__repr__',
#  '__rfloordiv__' => operator // on right operand
#  '__rlshift__',
#  '__rmatmul__',
#  '__rmod__',
#  '__rmul__' => operator * on right operand
#  '__ror__',
#  '__rpow__',
#  '__rrshift__',
#  '__rshift__',
#  '__rsub__' => operator - on right operand
#  '__rtruediv__' => operator / on right operand
#  '__rxor__',
#  '__setattr__',
#  '__setitem__',
#  '__setstate__',
#  '__sizeof__',
#  '__str__',
#  '__sub__' => operator - on left operand
#  '__subclasshook__',
#  '__truediv__' => operator / on left operand
#  '__xor__']

In [103]:
print(4.4 + 4) # method float.__add__ : OK
print()
print(4 + 4.4) # method int.__add__ : NotImplemented => float.__radd__
print()
print(a4 + 4) # method ndarray.__add__: OK
print()
print(4 + a4) # # method int.__add__ : NotImplemented => ndarray.__radd__

8.4

8.4

[[12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]]

[[12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]]


In [105]:
x = 4
x.__add__(4.4)

NotImplemented

In [106]:
x.__add__(a4)

NotImplemented

In [111]:
divmod(a4+1, 2)

(array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [112]:
a4 > 2

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [113]:
a4[0,0] = 2.0
a4

array([[2., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [114]:
a4 == 2.0

array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [115]:
a5 = a4**2
a5

array([[ 4., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64., 64., 64., 64., 64., 64.]])

In [118]:
# ndarray 'and' raises exception
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
# (a5 > 2) and (a4 < 100)

In [119]:
# and bitwise (numpy => elementwise)
(a5 > 2) & (a4 < 100)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [120]:
# use str conversion => __str__
print(a4)

[[2. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]


In [121]:
# use repr conversion => __repr__
a4

array([[2., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [123]:
# date.__str__ => ISO format
print(d)
# date.__repr__ => type + attribute 
d

2024-02-29


datetime.date(2024, 2, 29)