# Object Oriented Programming in Python

In [1]:
import numpy as np
import pandas as pd
from datetime import date, datetime, time
import pytz
from city import City, CoastalCity

## Constructor

In [2]:
# build an instance of class range
r = range(100)
r

range(0, 100)

In [3]:
type(r)

range

In [4]:
# constructor class list adapt iterable object into a list
l = list(r)
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [5]:
list()

[]

In [6]:
inputCount = '125'
count = int(inputCount)
count

125

In [7]:
# ValueError: invalid literal for int() with base 10: 'not an integer'
# int('not an integer')

In [8]:
for inputFloat in '12.5', '1.345E-23', 'NaN', 'inf':
    f = float(inputFloat)
    print(f)

12.5
1.345e-23
nan
inf


In [9]:
df = pd.DataFrame(
    (
        ("Pau", 77000, 64),
        ("Toulouse", 470000, 31),
        ("Montpellier", 290000, 34),
    ),
    columns=['name', 'population', 'department']
)
df

name  population  department
0          Pau       77000          64
1     Toulouse      470000          31
2  Montpellier      290000          34

In [10]:
 type(df)

pandas.core.frame.DataFrame

In [11]:
# constructor ndarray: exists but not to be used directly
# => use functions instead
a = np.ndarray((5,5))
a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78019082e-306, 7.56596412e-307],
       [1.33511018e-306, 1.33511969e-306, 6.23037996e-307,
        1.69121639e-306, 1.95821439e-306],
       [6.23037657e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307],
       [7.56601165e-307, 1.69118787e-306, 1.60220393e-306,
        1.37961302e-306, 1.78021798e-306],
       [1.37961709e-306, 2.22522597e-306, 1.24610791e-306,
        1.42410974e-306, 1.43868439e-133]])

In [12]:
a1 = np.empty((10,10))
a2 = np.zeros((10,10))
a3 = np.random.normal(12.0, 3.5, (10,10))

In [13]:
a1

array([[0.00000000e+000, 6.95167694e-310, 3.77960219e-321,
                    nan, 8.49074123e-312, 1.20480715e+132,
        1.57211607e-076, 1.08560026e-095, 1.72399088e-047,
        7.26429152e-043],
       [6.38854490e-067, 1.65618616e-076, 6.01347002e-154,
        2.09129559e-076, 3.57280050e-062, 1.44923058e-047,
        5.20267279e-090, 5.98149210e-154, 3.48987493e-086,
        5.05117287e-038],
       [4.57671243e-072, 1.72371734e-047, 1.05206135e-153,
        4.46814865e-033, 1.08560026e-095, 6.01347002e-154,
        1.02964652e-071, 1.10844292e-047, 8.97921055e-067,
        1.65618618e-076],
       [6.01346953e-154, 4.41943885e-062, 5.20748184e-090,
        5.60302081e-067, 3.27550830e+179, 5.05218193e-086,
        2.17767177e-076, 2.44006303e-154, 2.36942783e-038,
        6.12580295e-062],
       [1.05220702e-153, 3.11775839e-033, 1.10455295e+141,
        6.01347002e-154, 1.91824408e-076, 1.65618616e-076,
        1.42692839e-071, 3.57280977e-062, 1.91553993e-076,
        5.2

In [14]:
a2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
a3

array([[13.71005091, 13.98101781, 12.02773718, 10.61560857, 16.12594275,
        12.29596413, 15.78196758,  8.88526584, 13.4394442 , 10.81295451],
       [12.46805601, 10.14310934, 10.33551512, 10.41014766, 15.38994353,
        12.03719318, 14.5251071 , 20.25415044, 11.03415793, 11.8467193 ],
       [ 5.05959074, 13.05678039, 10.62224044, 12.39845392, 11.71222625,
        17.09618669, 12.84651716, 19.96351755,  9.54620764,  7.73261092],
       [ 8.00520307, 14.88232193, 13.07547014, 14.68827591, 13.01161308,
        11.81763339,  5.50507766, 14.90748629, 16.9454591 ,  7.09809132],
       [11.90044644, 13.58838171, 10.72212968, 18.37181104, 12.94046609,
         9.53717799, 11.89433753, 10.31396526, 12.22500299, 14.33824616],
       [12.42098983, 11.20641858, 13.47756241, 15.88407606, 12.5978636 ,
        13.30257298, 13.03355695, 12.1810657 , 18.2597884 ,  4.19938004],
       [ 8.82093525, 13.44831545, 18.90276829,  9.40728682, 10.32436508,
        14.3851677 , 13.19241961, 17.72056231

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
tz = pytz.timezone('America/La_Paz')
d = date(2024, 2, 29)
dt = datetime(2024, 2, 29, 14, 30)
dt2 = datetime(2024, 2, 29, 14, 30, 20, 125001, tz)
d, dt, dt2

(datetime.date(2024, 2, 29),
 datetime.datetime(2024, 2, 29, 14, 30),
 datetime.datetime(2024, 2, 29, 14, 30, 20, 125001, tzinfo=<DstTzInfo 'America/La_Paz' LMT-1 day, 19:27:00 STD>))

In [18]:
# build temporal object without constructor
d2 = date.today()
dt3 = datetime.now()
dt4 = datetime.now(tz)
d2, dt3, dt3.time(), dt4

(datetime.date(2024, 2, 8),
 datetime.datetime(2024, 2, 8, 9, 45, 46, 40917),
 datetime.time(9, 45, 46, 40917),
 datetime.datetime(2024, 2, 8, 4, 45, 46, 40917, tzinfo=<DstTzInfo 'America/La_Paz' -04-1 day, 20:00:00 STD>))

Summary:
- class = object type (model)
- object = instance of a class

## Attributes
- attribute = data part of an object

In [19]:
d.year, d.month, d.day

(2024, 2, 29)

In [20]:
dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second, dt.microsecond, dt.tzinfo

(2024, 2, 29, 14, 30, 0, 0, None)

In [21]:
a3.shape

(10, 10)

In [22]:
a3.dtype

dtype('float64')

In [23]:
a3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [24]:
# DataFrame: dynamic attribute for each column (when possible)
df.name

0            Pau
1       Toulouse
2    Montpellier
Name: name, dtype: object

## Methods and operators

### visible methods
start with a letter

In [25]:
# append method of class list
l.append(12)

In [26]:
l.append

<function list.append(object, /)>

In [27]:
dt.time()

datetime.time(14, 30)

In [28]:
dt.time

<function datetime.time>

In [29]:
d.strftime("%d/%m/%Y")

'29/02/2024'

#### ndarray methods

In [30]:
print(a3.sum(axis=1)) # rows
print(a3.sum(axis=0)) # columns

[127.67595347 128.44409961 120.0343317  119.93663189 125.83196489
 126.56327454 134.59054316 121.09879998 122.77044994 108.38185347]
[109.35287755 117.85573141 124.18006327 122.57257372 117.1611384
 131.24167317 128.79157023 148.17712565 130.51800524 105.477144  ]


In [31]:
a3.diagonal()

array([13.71005091, 10.14310934, 10.62224044, 14.68827591, 12.94046609,
       13.30257298, 13.19241961,  8.73258702, 14.10813362,  8.12257811])

In [32]:
a3[::-1].diagonal()

array([10.03848656,  4.71894861, 12.30086618,  9.40728682, 12.5978636 ,
        9.53717799,  5.50507766, 19.96351755, 11.03415793, 10.81295451])

### Masked methods
name: ```__mymethod__```
usage: 
- operator (```__add__```)
- builtin function: len (```__len__```)
- with block: ```__enter__, __exit__```

In [33]:
len(l)

101

In [34]:
l.__len__

<method-wrapper '__len__' of list object at 0x00000190255ED300>

In [35]:
l.__len__()

101

In [36]:
# DataFrame: len = number of rows
len(df)

3

In [37]:
# ndarray: size of first dimension
len(a3)

10

In [38]:
# TypeError: object of type 'int' has no len()
# len(123)

In [39]:
[1, 2, 3] + [7, 8, 9]

[1, 2, 3, 7, 8, 9]

In [40]:
list.__add__

<slot wrapper '__add__' of 'list' objects>

In [41]:
a1 + a2

array([[0.00000000e+000, 6.95167694e-310, 3.77960219e-321,
                    nan, 8.49074123e-312, 1.20480715e+132,
        1.57211607e-076, 1.08560026e-095, 1.72399088e-047,
        7.26429152e-043],
       [6.38854490e-067, 1.65618616e-076, 6.01347002e-154,
        2.09129559e-076, 3.57280050e-062, 1.44923058e-047,
        5.20267279e-090, 5.98149210e-154, 3.48987493e-086,
        5.05117287e-038],
       [4.57671243e-072, 1.72371734e-047, 1.05206135e-153,
        4.46814865e-033, 1.08560026e-095, 6.01347002e-154,
        1.02964652e-071, 1.10844292e-047, 8.97921055e-067,
        1.65618618e-076],
       [6.01346953e-154, 4.41943885e-062, 5.20748184e-090,
        5.60302081e-067, 3.27550830e+179, 5.05218193e-086,
        2.17767177e-076, 2.44006303e-154, 2.36942783e-038,
        6.12580295e-062],
       [1.05220702e-153, 3.11775839e-033, 1.10455295e+141,
        6.01347002e-154, 1.91824408e-076, 1.65618616e-076,
        1.42692839e-071, 3.57280977e-062, 1.91553993e-076,
        5.2

In [42]:
np.ndarray.__add__

<slot wrapper '__add__' of 'numpy.ndarray' objects>

In [43]:
a4 = a1 + 4
a4

array([[4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
                    nan, 4.00000000e+000, 1.20480715e+132,
        4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000, 3.27550830e+179, 4.00000000e+000,
        4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [4.00000000e+000, 4.00000000e+000, 1.10455295e+141,
        4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.0

In [44]:
# method called: __iadd__
a4 += 2
a4

array([[6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
                    nan, 6.00000000e+000, 1.20480715e+132,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 3.27550830e+179, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 1.10455295e+141,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.0

In [45]:
dir(a4)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [46]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [47]:
[ m for m in dir(a4) if 'add' in m ]

['__add__', '__iadd__', '__radd__']

In [48]:
city = "Pau"
[ m for m in dir(city) if 'add' in m ]

['__add__']

In [49]:
# when __iadd__ is not available, __add__ is called (new object)
# city = city.__add__(", city of king Henri IV")
city += ", city of king Henri IV"
city

'Pau, city of king Henri IV'

In [50]:
[ m for m in dir(a4) if m.startswith('__') ]

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new_

In [51]:
# '__abs__' => builtin function abs
#  '__add__' => operator + on left operand
#  '__and__' => operator &
#  '__array__',
#  '__array_finalize__',
#  '__array_function__',
#  '__array_interface__',
#  '__array_prepare__',
#  '__array_priority__',
#  '__array_struct__',
#  '__array_ufunc__',
#  '__array_wrap__',
#  '__bool__',
#  '__buffer__',
#  '__class__',
#  '__class_getitem__',
#  '__complex__',
#  '__contains__',
#  '__copy__',
#  '__deepcopy__',
#  '__delattr__',
#  '__delitem__',
#  '__dir__',
#  '__divmod__' => builtin function divmod()
#  '__dlpack__',
#  '__dlpack_device__',
#  '__doc__',
#  '__eq__' => operator ==
#  '__float__',
#  '__floordiv__' => operator // on left operand
#  '__format__',
#  '__ge__' => operator >= (greater or equal)
#  '__getattribute__',
#  '__getitem__',
#  '__getstate__',
#  '__gt__' => operator >= (greater)
#  '__hash__',
#  '__iadd__' => operator +=
#  '__iand__',
#  '__ifloordiv__',
#  '__ilshift__',
#  '__imatmul__',
#  '__imod__',
#  '__imul__',
#  '__index__',
#  '__init__',
#  '__init_subclass__',
#  '__int__',
#  '__invert__',
#  '__ior__',
#  '__ipow__',
#  '__irshift__',
#  '__isub__',
#  '__iter__',
#  '__itruediv__',
#  '__ixor__',
#  '__le__' => operator <= (less or equal)
#  '__len__' => builtin function len()
#  '__lshift__',
#  '__lt__' => operator < (less than)
#  '__matmul__',
#  '__mod__' => operator % on left operand
#  '__mul__' => operator * on left operand
#  '__ne__' => operator != (not equals)
#  '__neg__',
#  '__new__',
#  '__or__',
#  '__pos__',
#  '__pow__' => operator ?? on left operand
#  '__radd__' => operator + on right operand
#  '__rand__',
#  '__rdivmod__' => builtin function divmod on right operand
#  '__reduce__',
#  '__reduce_ex__',
#  '__repr__',
#  '__rfloordiv__' => operator // on right operand
#  '__rlshift__',
#  '__rmatmul__',
#  '__rmod__',
#  '__rmul__' => operator * on right operand
#  '__ror__',
#  '__rpow__',
#  '__rrshift__',
#  '__rshift__',
#  '__rsub__' => operator - on right operand
#  '__rtruediv__' => operator / on right operand
#  '__rxor__',
#  '__setattr__',
#  '__setitem__',
#  '__setstate__',
#  '__sizeof__',
#  '__str__',
#  '__sub__' => operator - on left operand
#  '__subclasshook__',
#  '__truediv__' => operator / on left operand
#  '__xor__']

In [52]:
print(4.4 + 4) # method float.__add__ : OK
print()
print(4 + 4.4) # method int.__add__ : NotImplemented => float.__radd__
print()
print(a4 + 4) # method ndarray.__add__: OK
print()
print(4 + a4) # # method int.__add__ : NotImplemented => ndarray.__radd__

8.4

8.4

[[1.00000000e+001 1.00000000e+001 1.00000000e+001             nan
  1.00000000e+001 1.20480715e+132 1.00000000e+001 1.00000000e+001
  1.00000000e+001 1.00000000e+001]
 [1.00000000e+001 1.00000000e+001 1.00000000e+001 1.00000000e+001
  1.00000000e+001 1.00000000e+001 1.00000000e+001 1.00000000e+001
  1.00000000e+001 1.00000000e+001]
 [1.00000000e+001 1.00000000e+001 1.00000000e+001 1.00000000e+001
  1.00000000e+001 1.00000000e+001 1.00000000e+001 1.00000000e+001
  1.00000000e+001 1.00000000e+001]
 [1.00000000e+001 1.00000000e+001 1.00000000e+001 1.00000000e+001
  3.27550830e+179 1.00000000e+001 1.00000000e+001 1.00000000e+001
  1.00000000e+001 1.00000000e+001]
 [1.00000000e+001 1.00000000e+001 1.10455295e+141 1.00000000e+001
  1.00000000e+001 1.00000000e+001 1.00000000e+001 1.00000000e+001
  1.00000000e+001 1.00000000e+001]
 [1.00000000e+001 1.00000000e+001 2.94814671e+179 1.00000000e+001
  1.00000000e+001 1.00000000e+001 8.94213159e+130 1.00000000e+001
  1.00000000e+001 1.000

In [53]:
x = 4
x.__add__(4.4)

NotImplemented

In [54]:
x.__add__(a4)

NotImplemented

In [55]:
divmod(a4+1, 2)

(array([[3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
                     nan, 3.00000000e+000, 6.02403574e+131,
         3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000],
        [3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000],
        [3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000],
        [3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000, 1.63775415e+179, 3.00000000e+000,
         3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000],
        [3.00000000e+000, 3.00000000e+000, 5.52276476e+140,
         3.00000000e+000, 3.00000000e+000, 3.00000000e+000,
         3.00000000e+000, 3.00000000e+000, 3.0000000

In [56]:
a4 > 2

array([[ True,  True,  True, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [57]:
a4[0,0] = 2.0
a4

array([[2.00000000e+000, 6.00000000e+000, 6.00000000e+000,
                    nan, 6.00000000e+000, 1.20480715e+132,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 3.27550830e+179, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 1.10455295e+141,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.0

In [58]:
a4 == 2.0

array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [59]:
a5 = a4**2
a5

C:\Users\Matthias\AppData\Local\Temp\ipykernel_13948\82979795.py:1: RuntimeWarning: overflow encountered in square
  a5 = a4**2


array([[4.00000000e+000, 3.60000000e+001, 3.60000000e+001,
                    nan, 3.60000000e+001, 1.45156026e+264,
        3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001],
       [3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001],
       [3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001],
       [3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001,             inf, 3.60000000e+001,
        3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001],
       [3.60000000e+001, 3.60000000e+001, 1.22003722e+282,
        3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.60000000e+001, 3.60000000e+001, 3.60000000e+001,
        3.6

In [60]:
# ndarray 'and' raises exception
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
# (a5 > 2) and (a4 < 100)

In [61]:
# and bitwise (numpy => elementwise)
(a5 > 2) & (a4 < 100)

array([[ True,  True,  True, False,  True, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [False,  True,  True,  True,  True, False,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True, False,  True,  True, False,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True, False,
         True]])

In [62]:
# use str conversion => __str__
print(a4)

[[2.00000000e+000 6.00000000e+000 6.00000000e+000             nan
  6.00000000e+000 1.20480715e+132 6.00000000e+000 6.00000000e+000
  6.00000000e+000 6.00000000e+000]
 [6.00000000e+000 6.00000000e+000 6.00000000e+000 6.00000000e+000
  6.00000000e+000 6.00000000e+000 6.00000000e+000 6.00000000e+000
  6.00000000e+000 6.00000000e+000]
 [6.00000000e+000 6.00000000e+000 6.00000000e+000 6.00000000e+000
  6.00000000e+000 6.00000000e+000 6.00000000e+000 6.00000000e+000
  6.00000000e+000 6.00000000e+000]
 [6.00000000e+000 6.00000000e+000 6.00000000e+000 6.00000000e+000
  3.27550830e+179 6.00000000e+000 6.00000000e+000 6.00000000e+000
  6.00000000e+000 6.00000000e+000]
 [6.00000000e+000 6.00000000e+000 1.10455295e+141 6.00000000e+000
  6.00000000e+000 6.00000000e+000 6.00000000e+000 6.00000000e+000
  6.00000000e+000 6.00000000e+000]
 [6.00000000e+000 6.00000000e+000 2.94814671e+179 6.00000000e+000
  6.00000000e+000 6.00000000e+000 8.94213159e+130 6.00000000e+000
  6.00000000e+000 6.00000000e+000

In [63]:
# use repr conversion => __repr__
a4

array([[2.00000000e+000, 6.00000000e+000, 6.00000000e+000,
                    nan, 6.00000000e+000, 1.20480715e+132,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 3.27550830e+179, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000],
       [6.00000000e+000, 6.00000000e+000, 1.10455295e+141,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.00000000e+000, 6.00000000e+000, 6.00000000e+000,
        6.0

In [64]:
# date.__str__ => ISO format
print(d)
# date.__repr__ => type + attribute 
d

2024-02-29


datetime.date(2024, 2, 29)

## Iterable / Iterator

In [65]:
city = 'Toulouse'
for letter in city:
    print(letter)

T
o
u
l
o
u
s
e


In [66]:
city.__iter__

<method-wrapper '__iter__' of str object at 0x00000190255F6270>

In [67]:
it = iter(city) # call __iter__
it

In [68]:
it2 = iter(l)
it2

In [69]:
# builtin next calls __next__ (go to next element and retrieve current element)
next(it)

'T'

In [70]:
# execute n times this cell until having exception StopIteration
next(it)

'o'

In [71]:
# equivalent of a loop for with explicit iterator
it = iter(city)
while True:
    try:
        letter = next(it)
        # do something with letter
        print(letter)
    except StopIteration:
        break # exit while loop

T
o
u
l
o
u
s
e


In [72]:
# list.extend can use any iterable source
l0 = [ 1, 2 ]
l0.extend([3, 4])
print(l0)
l0.extend((5,6))
print(l0)
l0.extend('Toulouse')
print(l0)

[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 'T', 'o', 'u', 'l', 'o', 'u', 's', 'e']


In [73]:
l0.extend?

Signature: l0.extend(iterable, /)
Docstring: Extend list by appending elements from the iterable.
Type:      builtin_function_or_method

### builtin functions using iterable

In [74]:
sum?

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

In [75]:
sum(l)

4962

In [76]:
# sum(city, start='')
'-'.join(city)

'T-o-u-l-o-u-s-e'

In [77]:
min(l), max(l)

(0, 99)

In [78]:
# lazy evaluation
e = enumerate(city, start=1)
e

In [79]:
letter_number_list = list(e)
letter_number_list

[(1, 'T'),
 (2, 'o'),
 (3, 'u'),
 (4, 'l'),
 (5, 'o'),
 (6, 'u'),
 (7, 's'),
 (8, 'e')]

In [80]:
zip?

Init signature: zip(self, /, *args, **kwargs)
Docstring:     
zip(*iterables, strict=False) --> Yield tuples until an input is exhausted.

   >>> list(zip('abcdefg', range(3), range(4)))
   [('a', 0, 0), ('b', 1, 1), ('c', 2, 2)]

The zip object yields n-length tuples, where n is the number of iterables
passed as positional arguments to zip().  The i-th element in every tuple
comes from the i-th iterable argument to zip().  This continues until the
shortest argument is exhausted.

If strict is true and one of the arguments is exhausted before the others,
raise a ValueError.
Type:           type
Subclasses:     

In [81]:
zip()

In [82]:
zip(city)

In [83]:
z = zip(city, range(1000, 2000))
z

In [84]:
letter_number_list2 = list(z)
letter_number_list2

[('T', 1000),
 ('o', 1001),
 ('u', 1002),
 ('l', 1003),
 ('o', 1004),
 ('u', 1005),
 ('s', 1006),
 ('e', 1007)]

In [85]:
list(zip(city, [1, 3, 5, 7], (True, False, False, True)))

[('T', 1, True), ('o', 3, False), ('u', 5, False), ('l', 7, True)]

In [86]:
for letter, n, ok in zip(city, [1, 3, 5, 7], (True, False, False, True)):
    print(letter, n, ok)

T 1 True
o 3 False
u 5 False
l 7 True


### generator

In [87]:
# for expression => generator
g = (x**2 + 1 for x in range(10))
g

<generator object <genexpr> at 0x00000190255E36B0>

In [88]:
# list comprehension
values = [ x**2 + 1 for x in range(10) ]
values

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]

In [89]:
values2 = list(g)
values2

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]

In [90]:
list(g)

[]

In [91]:
# don't need extra parenthesis
sum(x**2 + 1 for x in range(10))

295

In [92]:
# if 2+ args, need parenthesis
# SyntaxError: Generator expression must be parenthesized
# sum(x**2 + 1 for x in range(10), start=5)

In [93]:
sum((x**2 + 1 for x in range(10)), start=5)

300

In [94]:
# good practice
s1 = sum(x**2 + 1 for x in range(10_000_000)) # use 2 ints max

# bad practice (memory peak)
s2 = sum([ x**2 + 1 for x in range(10_000_000) ]) # use 10_000_000 ints + accumulator

# same results
s1, s2

(333333283333345000000, 333333283333345000000)

In [95]:
g = (x**2 + 1 for x in range(10))
g

<generator object <genexpr> at 0x00000190255E3850>

In [96]:
# exexcution n times this cell
# iterate on generator
next(g)

1

In [97]:
# a generator is Iterable
# the iteror of a generator is itself
iter(g) is g

True

In [98]:
it = iter(l)
assert it is not l
assert iter(it) is it
assert iter(iter(it)) is it

## Inheritance

In [99]:
city = City('Pau', 77_000, 64)
coastalCity = CoastalCity("Bayonne", 49_000, 64, "Atlantic Ocean")

In [100]:
# a coastal city has all attributes from City class
print(coastalCity.name)
print(coastalCity.population)
print(coastalCity.department)
# plus new attribute
print(coastalCity.marine)

Bayonne
49000
64
Atlantic Ocean


In [101]:
# a coastal city has all methods from City class
coastalCity.populationDifference(city)

-28000

In [102]:
# LSP on argument method
city.populationDifference(coastalCity)

28000

In [103]:
# same operators and builtins implementation
print(coastalCity)
print(repr(coastalCity))
coastalCity += 100000

Bayonne (pop=49000, dept=64) near Atlantic Ocean
CoastalCity[Bayonne, pop=49000, dept=64, marine=Atlantic Ocean]


In [104]:
# real types: object create from this class
print(type(city))
print(type(coastalCity))

<class 'city.City'>
<class 'city.CoastalCity'>


In [108]:
# isinstance (LSP)
print("CoastalCity:")
print("\t- is as CoastalCity:", isinstance(coastalCity, CoastalCity))
print("\t- is as City:", isinstance(coastalCity, City))
print("\t- is as object:", isinstance(coastalCity, object))
print("City:")
print("\t- is as City:", isinstance(city, City))
print("\t- is as CoastalCity:", isinstance(city, CoastalCity))

CoastalCity:
	- is as CoastalCity: True
	- is as City: True
	- is as object: True
City:
	- is as City: True
	- is as CoastalCity: False


In [106]:
city < coastalCity

False

In [109]:
#NB: cf also MaskedArray sub-class of ndarray masking values (NaN, out of range)

## Properties

### City case: no properties

In [111]:
# no control at assignment
city.population = -10000
city

City[Pau, pop=-10000, dept=64]

In [112]:
# remove attribute !
del city.population

In [114]:
# AttributeError: 'City' object has no attribute 'population'
# city

In [116]:
# add attributes
city.population = 10
city.area = 125000
city

City[Pau, pop=10, dept=64]

### ndarray case: all properties
attributes are in fact properties

a property = hidden attribute + 3 optional methods (getter, setter, deletter)

In [119]:
print(a3.shape)
a3.shape = (20, 5) # ok compatible
print(a3.shape)
a3

(10, 10)
(20, 5)


array([[13.71005091, 13.98101781, 12.02773718, 10.61560857, 16.12594275],
       [12.29596413, 15.78196758,  8.88526584, 13.4394442 , 10.81295451],
       [12.46805601, 10.14310934, 10.33551512, 10.41014766, 15.38994353],
       [12.03719318, 14.5251071 , 20.25415044, 11.03415793, 11.8467193 ],
       [ 5.05959074, 13.05678039, 10.62224044, 12.39845392, 11.71222625],
       [17.09618669, 12.84651716, 19.96351755,  9.54620764,  7.73261092],
       [ 8.00520307, 14.88232193, 13.07547014, 14.68827591, 13.01161308],
       [11.81763339,  5.50507766, 14.90748629, 16.9454591 ,  7.09809132],
       [11.90044644, 13.58838171, 10.72212968, 18.37181104, 12.94046609],
       [ 9.53717799, 11.89433753, 10.31396526, 12.22500299, 14.33824616],
       [12.42098983, 11.20641858, 13.47756241, 15.88407606, 12.5978636 ],
       [13.30257298, 13.03355695, 12.1810657 , 18.2597884 ,  4.19938004],
       [ 8.82093525, 13.44831545, 18.90276829,  9.40728682, 10.32436508],
       [14.3851677 , 13.19241961, 17.7

In [128]:
a3.shape = (100,)
a3

array([13.71005091, 13.98101781, 12.02773718, 10.61560857, 16.12594275,
       12.29596413, 15.78196758,  8.88526584, 13.4394442 , 10.81295451,
       12.46805601, 10.14310934, 10.33551512, 10.41014766, 15.38994353,
       12.03719318, 14.5251071 , 20.25415044, 11.03415793, 11.8467193 ,
        5.05959074, 13.05678039, 10.62224044, 12.39845392, 11.71222625,
       17.09618669, 12.84651716, 19.96351755,  9.54620764,  7.73261092,
        8.00520307, 14.88232193, 13.07547014, 14.68827591, 13.01161308,
       11.81763339,  5.50507766, 14.90748629, 16.9454591 ,  7.09809132,
       11.90044644, 13.58838171, 10.72212968, 18.37181104, 12.94046609,
        9.53717799, 11.89433753, 10.31396526, 12.22500299, 14.33824616,
       12.42098983, 11.20641858, 13.47756241, 15.88407606, 12.5978636 ,
       13.30257298, 13.03355695, 12.1810657 , 18.2597884 ,  4.19938004,
        8.82093525, 13.44831545, 18.90276829,  9.40728682, 10.32436508,
       14.3851677 , 13.19241961, 17.72056231, 11.39049879, 16.99

In [121]:
# attribute shape is protected against wrong modification
# ValueError: cannot reshape array of size 100 into shape (100,100)
# a3.shape = (100, 100)

In [125]:
# AttributeError: Cannot delete array data
# del a3.data

In [127]:
# AttributeError: 'numpy.ndarray' object has no attribute 'day'
# a3.day = 'Jeudi'

In [131]:
a10 = np.full(200, 40.0)
a10[100:] = a3
a10

array([40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.  