# Object Oriented Programming in Python

In [1]:
import numpy as np
import pandas as pd
from datetime import date, datetime, time
import pytz

## Constructor

In [2]:
# build an instance of class range
r = range(100)
r

range(0, 100)

In [3]:
type(r)

range

In [4]:
# constructor class list adapt iterable object into a list
l = list(r)
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [5]:
list()

[]

In [6]:
inputCount = '125'
count = int(inputCount)
count

125

In [7]:
# ValueError: invalid literal for int() with base 10: 'not an integer'
# int('not an integer')

In [8]:
for inputFloat in '12.5', '1.345E-23', 'NaN', 'inf':
    f = float(inputFloat)
    print(f)

12.5
1.345e-23
nan
inf


In [9]:
df = pd.DataFrame(
    (
        ("Pau", 77000, 64),
        ("Toulouse", 470000, 31),
        ("Montpellier", 290000, 34),
    ),
    columns=['name', 'population', 'department']
)
df

name  population  department
0          Pau       77000          64
1     Toulouse      470000          31
2  Montpellier      290000          34

In [10]:
 type(df)

pandas.core.frame.DataFrame

In [11]:
# constructor ndarray: exists but not to be used directly
# => use functions instead
a = np.ndarray((5,5))
a

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78019082e-306, 7.56596412e-307],
       [1.33511018e-306, 1.33511969e-306, 6.23037996e-307,
        1.69121639e-306, 1.95821439e-306],
       [6.23037657e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307],
       [7.56601165e-307, 1.69118787e-306, 1.60220393e-306,
        1.37961302e-306, 1.78021798e-306],
       [1.37961709e-306, 2.22522597e-306, 1.24610791e-306,
        1.42410974e-306, 2.56761491e-312]])

In [12]:
a1 = np.empty((10,10))
a2 = np.zeros((10,10))
a3 = np.random.normal(12.0, 3.5, (10,10))

In [13]:
a1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
a2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
a3

array([[11.01557355,  7.15799461, 14.77650468, 12.37523877, 10.35348364,
        11.1149751 , 12.74365846, 13.71651544, 13.54254175, 13.03679556],
       [19.90499004, 13.03258274, 11.60268508,  9.54145401, 11.60288101,
         5.94921843, 14.67512477,  7.45894287, 13.94811188, 10.30162894],
       [11.89101531, 12.22554039, 17.53435355, 15.97686513, 19.29631865,
        18.019914  , 11.91895062, 14.55237215, 15.78726713,  7.2024145 ],
       [15.66562954, 10.93123861,  8.92698069, 12.02757715,  7.69193706,
        10.65317104, 17.70294749,  9.99603872, 16.30656674, 14.3031994 ],
       [10.51081504, 16.05866572, 13.07867871, 12.87481554,  5.28188755,
         6.96774198, 14.95820241, 13.34743948, 16.76128381, 11.77029164],
       [11.0405215 , 12.33690693, 17.2988854 , 14.61565425,  7.44445608,
         5.34082893, 16.23754626, 10.61027172,  4.63816579,  8.48598537],
       [ 8.8127145 , 10.67424404, 13.49726712, 15.47096212, 16.42893901,
         5.13136124,  7.43742298, 11.81342886

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
tz = pytz.timezone('America/La_Paz')
d = date(2024, 2, 29)
dt = datetime(2024, 2, 29, 14, 30)
dt2 = datetime(2024, 2, 29, 14, 30, 20, 125001, tz)
d, dt, dt2

(datetime.date(2024, 2, 29),
 datetime.datetime(2024, 2, 29, 14, 30),
 datetime.datetime(2024, 2, 29, 14, 30, 20, 125001, tzinfo=<DstTzInfo 'America/La_Paz' LMT-1 day, 19:27:00 STD>))

In [18]:
# build temporal object without constructor
d2 = date.today()
dt3 = datetime.now()
dt4 = datetime.now(tz)
d2, dt3, dt3.time(), dt4

(datetime.date(2024, 2, 7),
 datetime.datetime(2024, 2, 7, 16, 28, 45, 501423),
 datetime.time(16, 28, 45, 501423),
 datetime.datetime(2024, 2, 7, 11, 28, 45, 501423, tzinfo=<DstTzInfo 'America/La_Paz' -04-1 day, 20:00:00 STD>))

Summary:
- class = object type (model)
- object = instance of a class

## Attributes
- attribute = data part of an object

In [19]:
d.year, d.month, d.day

(2024, 2, 29)

In [20]:
dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second, dt.microsecond, dt.tzinfo

(2024, 2, 29, 14, 30, 0, 0, None)

In [21]:
a3.shape

(10, 10)

In [22]:
a3.dtype

dtype('float64')

In [23]:
a3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [24]:
# DataFrame: dynamic attribute for each column (when possible)
df.name

0            Pau
1       Toulouse
2    Montpellier
Name: name, dtype: object

## Methods and operators

### visible methods
start with a letter

In [25]:
# append method of class list
l.append(12)

In [26]:
l.append

<function list.append(object, /)>

In [27]:
dt.time()

datetime.time(14, 30)

In [28]:
dt.time

<function datetime.time>

In [29]:
d.strftime("%d/%m/%Y")

'29/02/2024'

#### ndarray methods

In [99]:
print(a3.sum(axis=1)) # rows
print(a3.sum(axis=0)) # columns

[119.83328155 118.01761977 144.40501143 124.20528645 121.60982188
 108.04922221 120.65913165 121.60068078 123.97408998 139.84351104]
[123.0216634  118.7273665  134.74180711 135.33935292 118.42050545
  94.27644348 130.48726754 125.2849605  141.53736668 120.36092316]


In [100]:
a3.diagonal()

array([11.01557355, 13.03258274, 17.53435355, 12.02757715,  5.28188755,
        5.34082893,  7.43742298, 14.96476721, 14.83605262, 14.8715923 ])

In [102]:
a3[::-1].diagonal()

array([13.03660071, 12.89315506, 11.79290501, 15.47096212,  7.44445608,
        6.96774198, 17.70294749, 14.55237215, 13.94811188, 13.03679556])

### Masked methods
name: ```__mymethod__```
usage: 
- operator (```__add__```)
- builtin function: len (```__len__```)
- with block: ```__enter__, __exit__```

In [30]:
len(l)

101

In [31]:
l.__len__

<method-wrapper '__len__' of list object at 0x000001E6D3BE26C0>

In [32]:
l.__len__()

101

In [33]:
# DataFrame: len = number of rows
len(df)

3

In [34]:
# ndarray: size of first dimension
len(a3)

10

In [35]:
# TypeError: object of type 'int' has no len()
# len(123)

In [36]:
[1, 2, 3] + [7, 8, 9]

[1, 2, 3, 7, 8, 9]

In [37]:
list.__add__

<slot wrapper '__add__' of 'list' objects>

In [38]:
a1 + a2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.ndarray.__add__

<slot wrapper '__add__' of 'numpy.ndarray' objects>

In [40]:
a4 = a1 + 4
a4

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [41]:
# method called: __iadd__
a4 += 2
a4

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [42]:
dir(a4)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [43]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [44]:
[ m for m in dir(a4) if 'add' in m ]

['__add__', '__iadd__', '__radd__']

In [45]:
city = "Pau"
[ m for m in dir(city) if 'add' in m ]

['__add__']

In [46]:
# when __iadd__ is not available, __add__ is called (new object)
# city = city.__add__(", city of king Henri IV")
city += ", city of king Henri IV"
city

'Pau, city of king Henri IV'

In [47]:
[ m for m in dir(a4) if m.startswith('__') ]

['__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new_

In [48]:
# '__abs__' => builtin function abs
#  '__add__' => operator + on left operand
#  '__and__' => operator &
#  '__array__',
#  '__array_finalize__',
#  '__array_function__',
#  '__array_interface__',
#  '__array_prepare__',
#  '__array_priority__',
#  '__array_struct__',
#  '__array_ufunc__',
#  '__array_wrap__',
#  '__bool__',
#  '__buffer__',
#  '__class__',
#  '__class_getitem__',
#  '__complex__',
#  '__contains__',
#  '__copy__',
#  '__deepcopy__',
#  '__delattr__',
#  '__delitem__',
#  '__dir__',
#  '__divmod__' => builtin function divmod()
#  '__dlpack__',
#  '__dlpack_device__',
#  '__doc__',
#  '__eq__' => operator ==
#  '__float__',
#  '__floordiv__' => operator // on left operand
#  '__format__',
#  '__ge__' => operator >= (greater or equal)
#  '__getattribute__',
#  '__getitem__',
#  '__getstate__',
#  '__gt__' => operator >= (greater)
#  '__hash__',
#  '__iadd__' => operator +=
#  '__iand__',
#  '__ifloordiv__',
#  '__ilshift__',
#  '__imatmul__',
#  '__imod__',
#  '__imul__',
#  '__index__',
#  '__init__',
#  '__init_subclass__',
#  '__int__',
#  '__invert__',
#  '__ior__',
#  '__ipow__',
#  '__irshift__',
#  '__isub__',
#  '__iter__',
#  '__itruediv__',
#  '__ixor__',
#  '__le__' => operator <= (less or equal)
#  '__len__' => builtin function len()
#  '__lshift__',
#  '__lt__' => operator < (less than)
#  '__matmul__',
#  '__mod__' => operator % on left operand
#  '__mul__' => operator * on left operand
#  '__ne__' => operator != (not equals)
#  '__neg__',
#  '__new__',
#  '__or__',
#  '__pos__',
#  '__pow__' => operator ?? on left operand
#  '__radd__' => operator + on right operand
#  '__rand__',
#  '__rdivmod__' => builtin function divmod on right operand
#  '__reduce__',
#  '__reduce_ex__',
#  '__repr__',
#  '__rfloordiv__' => operator // on right operand
#  '__rlshift__',
#  '__rmatmul__',
#  '__rmod__',
#  '__rmul__' => operator * on right operand
#  '__ror__',
#  '__rpow__',
#  '__rrshift__',
#  '__rshift__',
#  '__rsub__' => operator - on right operand
#  '__rtruediv__' => operator / on right operand
#  '__rxor__',
#  '__setattr__',
#  '__setitem__',
#  '__setstate__',
#  '__sizeof__',
#  '__str__',
#  '__sub__' => operator - on left operand
#  '__subclasshook__',
#  '__truediv__' => operator / on left operand
#  '__xor__']

In [49]:
print(4.4 + 4) # method float.__add__ : OK
print()
print(4 + 4.4) # method int.__add__ : NotImplemented => float.__radd__
print()
print(a4 + 4) # method ndarray.__add__: OK
print()
print(4 + a4) # # method int.__add__ : NotImplemented => ndarray.__radd__

8.4

8.4

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


In [50]:
x = 4
x.__add__(4.4)

NotImplemented

In [51]:
x.__add__(a4)

NotImplemented

In [52]:
divmod(a4+1, 2)

(array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [53]:
a4 > 2

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [54]:
a4[0,0] = 2.0
a4

array([[2., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [55]:
a4 == 2.0

array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [56]:
a5 = a4**2
a5

array([[ 4., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36.]])

In [57]:
# ndarray 'and' raises exception
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
# (a5 > 2) and (a4 < 100)

In [58]:
# and bitwise (numpy => elementwise)
(a5 > 2) & (a4 < 100)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [59]:
# use str conversion => __str__
print(a4)

[[2. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]]


In [60]:
# use repr conversion => __repr__
a4

array([[2., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [61]:
# date.__str__ => ISO format
print(d)
# date.__repr__ => type + attribute 
d

2024-02-29


datetime.date(2024, 2, 29)

## Iterable / Iterator

In [62]:
city = 'Toulouse'
for letter in city:
    print(letter)

T
o
u
l
o
u
s
e


In [63]:
city.__iter__

<method-wrapper '__iter__' of str object at 0x000001E6D3BF4030>

In [64]:
it = iter(city) # call __iter__
it

In [65]:
it2 = iter(l)
it2

In [66]:
# builtin next calls __next__ (go to next element and retrieve current element)
next(it)

'T'

In [67]:
# execute n times this cell until having exception StopIteration
next(it)

'o'

In [68]:
# equivalent of a loop for with explicit iterator
it = iter(city)
while True:
    try:
        letter = next(it)
        # do something with letter
        print(letter)
    except StopIteration:
        break # exit while loop

T
o
u
l
o
u
s
e


In [69]:
# list.extend can use any iterable source
l0 = [ 1, 2 ]
l0.extend([3, 4])
print(l0)
l0.extend((5,6))
print(l0)
l0.extend('Toulouse')
print(l0)

[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 'T', 'o', 'u', 'l', 'o', 'u', 's', 'e']


In [70]:
l0.extend?

Signature: l0.extend(iterable, /)
Docstring: Extend list by appending elements from the iterable.
Type:      builtin_function_or_method

### builtin functions using iterable

In [71]:
sum?

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

In [72]:
sum(l)

4962

In [73]:
# sum(city, start='')
'-'.join(city)

'T-o-u-l-o-u-s-e'

In [74]:
min(l), max(l)

(0, 99)

In [75]:
# lazy evaluation
e = enumerate(city, start=1)
e

In [76]:
letter_number_list = list(e)
letter_number_list

[(1, 'T'),
 (2, 'o'),
 (3, 'u'),
 (4, 'l'),
 (5, 'o'),
 (6, 'u'),
 (7, 's'),
 (8, 'e')]

In [77]:
zip?

Init signature: zip(self, /, *args, **kwargs)
Docstring:     
zip(*iterables, strict=False) --> Yield tuples until an input is exhausted.

   >>> list(zip('abcdefg', range(3), range(4)))
   [('a', 0, 0), ('b', 1, 1), ('c', 2, 2)]

The zip object yields n-length tuples, where n is the number of iterables
passed as positional arguments to zip().  The i-th element in every tuple
comes from the i-th iterable argument to zip().  This continues until the
shortest argument is exhausted.

If strict is true and one of the arguments is exhausted before the others,
raise a ValueError.
Type:           type
Subclasses:     

In [78]:
zip()

In [79]:
zip(city)

In [80]:
z = zip(city, range(1000, 2000))
z

In [81]:
letter_number_list2 = list(z)
letter_number_list2

[('T', 1000),
 ('o', 1001),
 ('u', 1002),
 ('l', 1003),
 ('o', 1004),
 ('u', 1005),
 ('s', 1006),
 ('e', 1007)]

In [82]:
list(zip(city, [1, 3, 5, 7], (True, False, False, True)))

[('T', 1, True), ('o', 3, False), ('u', 5, False), ('l', 7, True)]

In [83]:
for letter, n, ok in zip(city, [1, 3, 5, 7], (True, False, False, True)):
    print(letter, n, ok)

T 1 True
o 3 False
u 5 False
l 7 True


### generator

In [84]:
# for expression => generator
g = (x**2 + 1 for x in range(10))
g

<generator object <genexpr> at 0x000001E6D3BCDF20>

In [85]:
# list comprehension
values = [ x**2 + 1 for x in range(10) ]
values

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]

In [86]:
values2 = list(g)
values2

[1, 2, 5, 10, 17, 26, 37, 50, 65, 82]

In [87]:
list(g)

[]

In [88]:
# don't need extra parenthesis
sum(x**2 + 1 for x in range(10))

295

In [89]:
# if 2+ args, need parenthesis
# SyntaxError: Generator expression must be parenthesized
# sum(x**2 + 1 for x in range(10), start=5)

In [90]:
sum((x**2 + 1 for x in range(10)), start=5)

300

In [91]:
# good practice
s1 = sum(x**2 + 1 for x in range(10_000_000)) # use 2 ints max

# bad practice (memory peak)
s2 = sum([ x**2 + 1 for x in range(10_000_000) ]) # use 10_000_000 ints + accumulator

# same results
s1, s2

(333333283333345000000, 333333283333345000000)

In [92]:
g = (x**2 + 1 for x in range(10))
g

<generator object <genexpr> at 0x000001E6D3CB02B0>

In [93]:
# exexcution n times this cell
# iterate on generator
next(g)

1

In [94]:
# a generator is Iterable
# the iteror of a generator is itself
iter(g) is g

True

In [95]:
it = iter(l)
assert it is not l
assert iter(it) is it
assert iter(iter(it)) is it